### PR TITLE
Handle plist-multi-file output format correctly

### PR DESCRIPTION
**Pull request by gerazo**
Fix for https://github.com/rizsotto/scan-build/issues/77

### CODE REVIEW

**Comment by rizsotto** [comment]
could you provide more details on the plist-multi-file output? the perl implementation does not support it... would not mind to add it, but i guess it needs more work then just add the flags to the argument parser. ;) builds are broken on every platform.

**Comment by gerazo** [comment]
plist-multi-file is the same as plist, but generates some extra information (used headers) into the plist xml. This information is needed by XTU analyzation in order to not drop analyzation data. We would like to use your scan-build in our XTU tooling because it is way better than the old one. Currently clang support 5 output formats: text, html, plist, plist-html, plist-multi-file as the output. The latter 3 needs a file as output, not a directory.

**Comment by gerazo** [comment]
I see that your implementation here is way more advanced than the one in the clang repo. What do you think, when will these changes be merged into clang?

**Comment by gerazo** [comment]
...and sorry for loading your servers with syntax problems. The settings are very strict. :)

**Comment by rizsotto** [comment]
thanks Zoltan, i still have the impression that it's not yet ready. (i miss to add command line arguments for the tools. also i would like to see a functional test case written for it.) anyway, there is a [pending pull-request](https://reviews.llvm.org/D26390) to Clang repo. you can subscribe to it if you like.
and you can check the syntax on your machine too before commits. `pep8` and `yapf` are good tools for it.

**Comment by gerazo** [comment]
I think it is ready. (One suite failed for some unknown reason.)

**Comment by rizsotto** [comment]
i've merged your pull-request to `devel` branch. (and did squash the commits into one.) will release when the Clang pull-request get merged. thank you!

**Comment by gerazo** [comment]
Thank you very much. Professional execution.

**Pull request closed without merging**
